// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backupnode.proto

package com.dfs.common.model.backup;

public interface BackupNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.BackupNodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hostname = 1;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional int32 port = 2;</code>
   */
  int getPort();
}
