// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backupnode.proto

package com.dfs.common.model.backup;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.BackupNodeSlots}
 */
public  final class BackupNodeSlots extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.BackupNodeSlots)
        BackupNodeSlotsOrBuilder {
  // Use BackupNodeSlots.newBuilder() to construct.
  private BackupNodeSlots(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BackupNodeSlots() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BackupNodeSlots(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              slots_ = com.google.protobuf.MapField.newMapField(
                  SlotsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<Integer, Integer>
            slots__ = input.readMessage(
                SlotsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            slots_.getMutableMap().put(
                slots__.getKey(), slots__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetSlots();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dfs.common.model.backup.BackupNodeSlots.class, com.dfs.common.model.backup.BackupNodeSlots.Builder.class);
  }

  public static final int SLOTS_FIELD_NUMBER = 1;
  private static final class SlotsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        Integer, Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<Integer, Integer>newDefaultInstance(
                com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_SlotsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      Integer, Integer> slots_;
  private com.google.protobuf.MapField<Integer, Integer>
  internalGetSlots() {
    if (slots_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SlotsDefaultEntryHolder.defaultEntry);
    }
    return slots_;
  }

  public int getSlotsCount() {
    return internalGetSlots().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; slots = 1;</code>
   */

  public boolean containsSlots(
      int key) {
    
    return internalGetSlots().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSlotsMap()} instead.
   */
  @Deprecated
  public java.util.Map<Integer, Integer> getSlots() {
    return getSlotsMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; slots = 1;</code>
   */

  public java.util.Map<Integer, Integer> getSlotsMap() {
    return internalGetSlots().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; slots = 1;</code>
   */

  public int getSlotsOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<Integer, Integer> map =
        internalGetSlots().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; slots = 1;</code>
   */

  public int getSlotsOrThrow(
      int key) {
    
    java.util.Map<Integer, Integer> map =
        internalGetSlots().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetSlots(),
        SlotsDefaultEntryHolder.defaultEntry,
        1);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<Integer, Integer> entry
         : internalGetSlots().getMap().entrySet()) {
      com.google.protobuf.MapEntry<Integer, Integer>
      slots__ = SlotsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, slots__);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dfs.common.model.backup.BackupNodeSlots)) {
      return super.equals(obj);
    }
    com.dfs.common.model.backup.BackupNodeSlots other = (com.dfs.common.model.backup.BackupNodeSlots) obj;

    boolean result = true;
    result = result && internalGetSlots().equals(
        other.internalGetSlots());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (!internalGetSlots().getMap().isEmpty()) {
      hash = (37 * hash) + SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSlots().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.BackupNodeSlots parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dfs.common.model.backup.BackupNodeSlots prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.BackupNodeSlots}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.BackupNodeSlots)
      com.dfs.common.model.backup.BackupNodeSlotsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSlots();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableSlots();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfs.common.model.backup.BackupNodeSlots.class, com.dfs.common.model.backup.BackupNodeSlots.Builder.class);
    }

    // Construct using com.dfs.common.model.backup.BackupNodeSlots.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableSlots().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_BackupNodeSlots_descriptor;
    }

    public com.dfs.common.model.backup.BackupNodeSlots getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    public com.dfs.common.model.backup.BackupNodeSlots build() {
      com.dfs.common.model.backup.BackupNodeSlots result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dfs.common.model.backup.BackupNodeSlots buildPartial() {
      com.dfs.common.model.backup.BackupNodeSlots result = new com.dfs.common.model.backup.BackupNodeSlots(this);
      int from_bitField0_ = bitField0_;
      result.slots_ = internalGetSlots();
      result.slots_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dfs.common.model.backup.BackupNodeSlots) {
        return mergeFrom((com.dfs.common.model.backup.BackupNodeSlots)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dfs.common.model.backup.BackupNodeSlots other) {
      if (other == getDefaultInstance()) return this;
      internalGetMutableSlots().mergeFrom(
          other.internalGetSlots());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dfs.common.model.backup.BackupNodeSlots parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dfs.common.model.backup.BackupNodeSlots) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        Integer, Integer> slots_;
    private com.google.protobuf.MapField<Integer, Integer>
    internalGetSlots() {
      if (slots_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SlotsDefaultEntryHolder.defaultEntry);
      }
      return slots_;
    }
    private com.google.protobuf.MapField<Integer, Integer>
    internalGetMutableSlots() {
      onChanged();;
      if (slots_ == null) {
        slots_ = com.google.protobuf.MapField.newMapField(
            SlotsDefaultEntryHolder.defaultEntry);
      }
      if (!slots_.isMutable()) {
        slots_ = slots_.copy();
      }
      return slots_;
    }

    public int getSlotsCount() {
      return internalGetSlots().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public boolean containsSlots(
        int key) {
      
      return internalGetSlots().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSlotsMap()} instead.
     */
    @Deprecated
    public java.util.Map<Integer, Integer> getSlots() {
      return getSlotsMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public java.util.Map<Integer, Integer> getSlotsMap() {
      return internalGetSlots().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public int getSlotsOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<Integer, Integer> map =
          internalGetSlots().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public int getSlotsOrThrow(
        int key) {
      
      java.util.Map<Integer, Integer> map =
          internalGetSlots().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSlots() {
      getMutableSlots().clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public Builder removeSlots(
        int key) {
      
      getMutableSlots().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<Integer, Integer>
    getMutableSlots() {
      return internalGetMutableSlots().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */
    public Builder putSlots(
        int key,
        int value) {
      
      
      getMutableSlots().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; slots = 1;</code>
     */

    public Builder putAllSlots(
        java.util.Map<Integer, Integer> values) {
      getMutableSlots().putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.BackupNodeSlots)
  }

  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.BackupNodeSlots)
  private static final com.dfs.common.model.backup.BackupNodeSlots DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dfs.common.model.backup.BackupNodeSlots();
  }

  public static com.dfs.common.model.backup.BackupNodeSlots getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BackupNodeSlots>
      PARSER = new com.google.protobuf.AbstractParser<BackupNodeSlots>() {
    public BackupNodeSlots parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BackupNodeSlots(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BackupNodeSlots> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BackupNodeSlots> getParserForType() {
    return PARSER;
  }

  public com.dfs.common.model.backup.BackupNodeSlots getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

