// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backupnode.proto

package com.dfs.common.model.backup;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchEditsLogRequest}
 */
public  final class FetchEditsLogRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.FetchEditsLogRequest)
        FetchEditsLogRequestOrBuilder {
  // Use FetchEditsLogRequest.newBuilder() to construct.
  private FetchEditsLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchEditsLogRequest() {
    txId_ = 0L;
    needSlots_ = false;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchEditsLogRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            txId_ = input.readInt64();
            break;
          }
          case 16: {

            needSlots_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_FetchEditsLogRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_FetchEditsLogRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dfs.common.model.backup.FetchEditsLogRequest.class, com.dfs.common.model.backup.FetchEditsLogRequest.Builder.class);
  }

  public static final int TXID_FIELD_NUMBER = 1;
  private long txId_;
  /**
   * <code>optional int64 txId = 1;</code>
   */
  public long getTxId() {
    return txId_;
  }

  public static final int NEEDSLOTS_FIELD_NUMBER = 2;
  private boolean needSlots_;
  /**
   * <code>optional bool needSlots = 2;</code>
   */
  public boolean getNeedSlots() {
    return needSlots_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (txId_ != 0L) {
      output.writeInt64(1, txId_);
    }
    if (needSlots_ != false) {
      output.writeBool(2, needSlots_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (txId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, txId_);
    }
    if (needSlots_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, needSlots_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dfs.common.model.backup.FetchEditsLogRequest)) {
      return super.equals(obj);
    }
    com.dfs.common.model.backup.FetchEditsLogRequest other = (com.dfs.common.model.backup.FetchEditsLogRequest) obj;

    boolean result = true;
    result = result && (getTxId()
        == other.getTxId());
    result = result && (getNeedSlots()
        == other.getNeedSlots());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTxId());
    hash = (37 * hash) + NEEDSLOTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedSlots());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.backup.FetchEditsLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dfs.common.model.backup.FetchEditsLogRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchEditsLogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.FetchEditsLogRequest)
      com.dfs.common.model.backup.FetchEditsLogRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_FetchEditsLogRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_FetchEditsLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfs.common.model.backup.FetchEditsLogRequest.class, com.dfs.common.model.backup.FetchEditsLogRequest.Builder.class);
    }

    // Construct using com.dfs.common.model.backup.FetchEditsLogRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      txId_ = 0L;

      needSlots_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dfs.common.model.backup.Backupnode.internal_static_com_ruyuan_dfs_common_proto_FetchEditsLogRequest_descriptor;
    }

    public com.dfs.common.model.backup.FetchEditsLogRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    public com.dfs.common.model.backup.FetchEditsLogRequest build() {
      com.dfs.common.model.backup.FetchEditsLogRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dfs.common.model.backup.FetchEditsLogRequest buildPartial() {
      com.dfs.common.model.backup.FetchEditsLogRequest result = new com.dfs.common.model.backup.FetchEditsLogRequest(this);
      result.txId_ = txId_;
      result.needSlots_ = needSlots_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dfs.common.model.backup.FetchEditsLogRequest) {
        return mergeFrom((com.dfs.common.model.backup.FetchEditsLogRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dfs.common.model.backup.FetchEditsLogRequest other) {
      if (other == getDefaultInstance()) return this;
      if (other.getTxId() != 0L) {
        setTxId(other.getTxId());
      }
      if (other.getNeedSlots() != false) {
        setNeedSlots(other.getNeedSlots());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dfs.common.model.backup.FetchEditsLogRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dfs.common.model.backup.FetchEditsLogRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long txId_ ;
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public long getTxId() {
      return txId_;
    }
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public Builder setTxId(long value) {
      
      txId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 txId = 1;</code>
     */
    public Builder clearTxId() {
      
      txId_ = 0L;
      onChanged();
      return this;
    }

    private boolean needSlots_ ;
    /**
     * <code>optional bool needSlots = 2;</code>
     */
    public boolean getNeedSlots() {
      return needSlots_;
    }
    /**
     * <code>optional bool needSlots = 2;</code>
     */
    public Builder setNeedSlots(boolean value) {
      
      needSlots_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool needSlots = 2;</code>
     */
    public Builder clearNeedSlots() {
      
      needSlots_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.FetchEditsLogRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.FetchEditsLogRequest)
  private static final com.dfs.common.model.backup.FetchEditsLogRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dfs.common.model.backup.FetchEditsLogRequest();
  }

  public static com.dfs.common.model.backup.FetchEditsLogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchEditsLogRequest>
      PARSER = new com.google.protobuf.AbstractParser<FetchEditsLogRequest>() {
    public FetchEditsLogRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchEditsLogRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchEditsLogRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FetchEditsLogRequest> getParserForType() {
    return PARSER;
  }

  public com.dfs.common.model.backup.FetchEditsLogRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

