// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.dfs.common.model.common;

public interface DataNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.DataNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hostname = 1;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional int32 nioPort = 2;</code>
   */
  int getNioPort();

  /**
   * <code>optional int32 httpPort = 3;</code>
   */
  int getHttpPort();
}
