// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package com.dfs.common.model.client;

public interface AuthenticateInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.AuthenticateInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string authenticateInfo = 1;</code>
   */
  String getAuthenticateInfo();
  /**
   * <code>optional string authenticateInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthenticateInfoBytes();
}
