// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package com.dfs.common.model.client;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.ruyuan.dfs.common.proto.DataNode dataNode = 1;</code>
   */
  boolean hasDataNode();
  /**
   * <code>optional .com.ruyuan.dfs.common.proto.DataNode dataNode = 1;</code>
   */
  com.dfs.common.model.common.DataNode getDataNode();
  /**
   * <code>optional .com.ruyuan.dfs.common.proto.DataNode dataNode = 1;</code>
   */
  com.dfs.common.model.common.DataNodeOrBuilder getDataNodeOrBuilder();

  /**
   * <code>optional string realFileName = 2;</code>
   */
  String getRealFileName();
  /**
   * <code>optional string realFileName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealFileNameBytes();
}
