// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package com.dfs.common.model.client;

public interface ReadStorageInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.ReadStorageInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 replica = 1;</code>
   */
  int getReplica();

  /**
   * <code>optional string datanodes = 2;</code>
   */
  String getDatanodes();
  /**
   * <code>optional string datanodes = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatanodesBytes();
}
