// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface ClientDataNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.ClientDataNodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  java.util.List<com.dfs.common.model.namenode.ClientDataNode> 
      getClientDataNodesList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  com.dfs.common.model.namenode.ClientDataNode getClientDataNodes(int index);
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  int getClientDataNodesCount();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  java.util.List<? extends com.dfs.common.model.namenode.ClientDataNodeOrBuilder> 
      getClientDataNodesOrBuilderList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  com.dfs.common.model.namenode.ClientDataNodeOrBuilder getClientDataNodesOrBuilder(
      int index);
}
