// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface FetchMetaDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  java.util.List<com.dfs.common.model.namenode.Metadata> 
      getFilesList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  com.dfs.common.model.namenode.Metadata getFiles(int index);
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  java.util.List<? extends com.dfs.common.model.namenode.MetadataOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  com.dfs.common.model.namenode.MetadataOrBuilder getFilesOrBuilder(
      int index);

  /**
   * <code>optional bool completed = 2;</code>
   */
  boolean getCompleted();

  /**
   * <code>optional int32 nodeId = 3;</code>
   */
  int getNodeId();
}
