// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface FetchDataNodeByFilenameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string filename = 1;</code>
   */
  String getFilename();
  /**
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
