// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse}
 */
public  final class FetchDataNodeByFilenameResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse)
        FetchDataNodeByFilenameResponseOrBuilder {
  // Use FetchDataNodeByFilenameResponse.newBuilder() to construct.
  private FetchDataNodeByFilenameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchDataNodeByFilenameResponse() {
    datanodes_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchDataNodeByFilenameResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              datanodes_ = new java.util.ArrayList<com.dfs.common.model.common.DataNode>();
              mutable_bitField0_ |= 0x00000001;
            }
            datanodes_.add(
                input.readMessage(com.dfs.common.model.common.DataNode.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        datanodes_ = java.util.Collections.unmodifiableList(datanodes_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse.class, com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse.Builder.class);
  }

  public static final int DATANODES_FIELD_NUMBER = 1;
  private java.util.List<com.dfs.common.model.common.DataNode> datanodes_;
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
   */
  public java.util.List<com.dfs.common.model.common.DataNode> getDatanodesList() {
    return datanodes_;
  }
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
   */
  public java.util.List<? extends com.dfs.common.model.common.DataNodeOrBuilder> 
      getDatanodesOrBuilderList() {
    return datanodes_;
  }
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
   */
  public int getDatanodesCount() {
    return datanodes_.size();
  }
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
   */
  public com.dfs.common.model.common.DataNode getDatanodes(int index) {
    return datanodes_.get(index);
  }
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
   */
  public com.dfs.common.model.common.DataNodeOrBuilder getDatanodesOrBuilder(
      int index) {
    return datanodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < datanodes_.size(); i++) {
      output.writeMessage(1, datanodes_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < datanodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, datanodes_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse)) {
      return super.equals(obj);
    }
    com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse other = (com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse) obj;

    boolean result = true;
    result = result && getDatanodesList()
        .equals(other.getDatanodesList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getDatanodesCount() > 0) {
      hash = (37 * hash) + DATANODES_FIELD_NUMBER;
      hash = (53 * hash) + getDatanodesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse)
      com.dfs.common.model.namenode.FetchDataNodeByFilenameResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse.class, com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse.Builder.class);
    }

    // Construct using com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDatanodesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (datanodesBuilder_ == null) {
        datanodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        datanodesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor;
    }

    public com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    public com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse build() {
      com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse buildPartial() {
      com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse result = new com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse(this);
      int from_bitField0_ = bitField0_;
      if (datanodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          datanodes_ = java.util.Collections.unmodifiableList(datanodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.datanodes_ = datanodes_;
      } else {
        result.datanodes_ = datanodesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse) {
        return mergeFrom((com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse other) {
      if (other == getDefaultInstance()) return this;
      if (datanodesBuilder_ == null) {
        if (!other.datanodes_.isEmpty()) {
          if (datanodes_.isEmpty()) {
            datanodes_ = other.datanodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatanodesIsMutable();
            datanodes_.addAll(other.datanodes_);
          }
          onChanged();
        }
      } else {
        if (!other.datanodes_.isEmpty()) {
          if (datanodesBuilder_.isEmpty()) {
            datanodesBuilder_.dispose();
            datanodesBuilder_ = null;
            datanodes_ = other.datanodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            datanodesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDatanodesFieldBuilder() : null;
          } else {
            datanodesBuilder_.addAllMessages(other.datanodes_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dfs.common.model.common.DataNode> datanodes_ =
      java.util.Collections.emptyList();
    private void ensureDatanodesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        datanodes_ = new java.util.ArrayList<com.dfs.common.model.common.DataNode>(datanodes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dfs.common.model.common.DataNode, com.dfs.common.model.common.DataNode.Builder, com.dfs.common.model.common.DataNodeOrBuilder> datanodesBuilder_;

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public java.util.List<com.dfs.common.model.common.DataNode> getDatanodesList() {
      if (datanodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(datanodes_);
      } else {
        return datanodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public int getDatanodesCount() {
      if (datanodesBuilder_ == null) {
        return datanodes_.size();
      } else {
        return datanodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public com.dfs.common.model.common.DataNode getDatanodes(int index) {
      if (datanodesBuilder_ == null) {
        return datanodes_.get(index);
      } else {
        return datanodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder setDatanodes(
        int index, com.dfs.common.model.common.DataNode value) {
      if (datanodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatanodesIsMutable();
        datanodes_.set(index, value);
        onChanged();
      } else {
        datanodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder setDatanodes(
        int index, com.dfs.common.model.common.DataNode.Builder builderForValue) {
      if (datanodesBuilder_ == null) {
        ensureDatanodesIsMutable();
        datanodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        datanodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder addDatanodes(com.dfs.common.model.common.DataNode value) {
      if (datanodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatanodesIsMutable();
        datanodes_.add(value);
        onChanged();
      } else {
        datanodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder addDatanodes(
        int index, com.dfs.common.model.common.DataNode value) {
      if (datanodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatanodesIsMutable();
        datanodes_.add(index, value);
        onChanged();
      } else {
        datanodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder addDatanodes(
        com.dfs.common.model.common.DataNode.Builder builderForValue) {
      if (datanodesBuilder_ == null) {
        ensureDatanodesIsMutable();
        datanodes_.add(builderForValue.build());
        onChanged();
      } else {
        datanodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder addDatanodes(
        int index, com.dfs.common.model.common.DataNode.Builder builderForValue) {
      if (datanodesBuilder_ == null) {
        ensureDatanodesIsMutable();
        datanodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        datanodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder addAllDatanodes(
        Iterable<? extends com.dfs.common.model.common.DataNode> values) {
      if (datanodesBuilder_ == null) {
        ensureDatanodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, datanodes_);
        onChanged();
      } else {
        datanodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder clearDatanodes() {
      if (datanodesBuilder_ == null) {
        datanodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        datanodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public Builder removeDatanodes(int index) {
      if (datanodesBuilder_ == null) {
        ensureDatanodesIsMutable();
        datanodes_.remove(index);
        onChanged();
      } else {
        datanodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public com.dfs.common.model.common.DataNode.Builder getDatanodesBuilder(
        int index) {
      return getDatanodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public com.dfs.common.model.common.DataNodeOrBuilder getDatanodesOrBuilder(
        int index) {
      if (datanodesBuilder_ == null) {
        return datanodes_.get(index);  } else {
        return datanodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public java.util.List<? extends com.dfs.common.model.common.DataNodeOrBuilder> 
         getDatanodesOrBuilderList() {
      if (datanodesBuilder_ != null) {
        return datanodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(datanodes_);
      }
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public com.dfs.common.model.common.DataNode.Builder addDatanodesBuilder() {
      return getDatanodesFieldBuilder().addBuilder(
          com.dfs.common.model.common.DataNode.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public com.dfs.common.model.common.DataNode.Builder addDatanodesBuilder(
        int index) {
      return getDatanodesFieldBuilder().addBuilder(
          index, com.dfs.common.model.common.DataNode.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    public java.util.List<com.dfs.common.model.common.DataNode.Builder> 
         getDatanodesBuilderList() {
      return getDatanodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dfs.common.model.common.DataNode, com.dfs.common.model.common.DataNode.Builder, com.dfs.common.model.common.DataNodeOrBuilder> 
        getDatanodesFieldBuilder() {
      if (datanodesBuilder_ == null) {
        datanodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dfs.common.model.common.DataNode, com.dfs.common.model.common.DataNode.Builder, com.dfs.common.model.common.DataNodeOrBuilder>(
                datanodes_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        datanodes_ = null;
      }
      return datanodesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse)
  private static final com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse();
  }

  public static com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchDataNodeByFilenameResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchDataNodeByFilenameResponse>() {
    public FetchDataNodeByFilenameResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchDataNodeByFilenameResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchDataNodeByFilenameResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FetchDataNodeByFilenameResponse> getParserForType() {
    return PARSER;
  }

  public com.dfs.common.model.namenode.FetchDataNodeByFilenameResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

