// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public final class Namenode {
  private Namenode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ControllerVote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ControllerVote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_OldSlotsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_OldSlotsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_NewSlotsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_NewSlotsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NewPeerNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NewPeerNodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RebalanceSlotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RebalanceSlotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RebalanceFetchMetadataCompletedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RebalanceFetchMetadataCompletedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RebalanceRemoveMetadataCompletedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RebalanceRemoveMetadataCompletedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_TrashResumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_TrashResumeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_UserEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_UserEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_UserList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ListFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ListFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_NameNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_NameNodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ClientDataNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016namenode.proto\022\033com.ruyuan.dfs.common." +
      "proto\032\rcommons.proto\032\016datanode.proto\"a\n\016" +
      "ControllerVote\022\023\n\013voterNodeId\030\001 \001(\005\022\030\n\020c" +
      "ontrollerNodeId\030\002 \001(\005\022\021\n\tvoteRound\030\003 \001(\005" +
      "\022\r\n\005force\030\004 \001(\010\"p\n\024NameNodeAwareRequest\022" +
      "\022\n\nnameNodeId\030\001 \001(\005\022\021\n\tnumOfNode\030\002 \001(\005\022\016" +
      "\n\006server\030\003 \001(\t\022\017\n\007servers\030\004 \003(\t\022\020\n\010isCli" +
      "ent\030\005 \001(\010\"\265\002\n\rNameNodeSlots\022J\n\010oldSlots\030" +
      "\001 \003(\01328.com.ruyuan.dfs.common.proto.Name" +
      "NodeSlots.OldSlotsEntry\022J\n\010newSlots\030\002 \003(",
      "\01328.com.ruyuan.dfs.common.proto.NameNode" +
      "Slots.NewSlotsEntry\022\021\n\trebalance\030\003 \001(\010\022\027" +
      "\n\017rebalanceNodeId\030\004 \001(\005\032/\n\rOldSlotsEntry" +
      "\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\032/\n\rNewS" +
      "lotsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028" +
      "\001\"\211\001\n\017NewPeerNodeInfo\022>\n\010requests\030\001 \003(\0132" +
      ",.com.ruyuan.dfs.common.proto.RegisterRe" +
      "quest\0226\n\005users\030\002 \003(\0132\'.com.ruyuan.dfs.co" +
      "mmon.proto.UserEntity\"+\n\025RebalanceSlotsR" +
      "equest\022\022\n\nnameNodeId\030\001 \001(\005\"5\n\024FetchMetaD",
      "ataRequest\022\r\n\005slots\030\001 \003(\005\022\016\n\006nodeId\030\002 \001(" +
      "\005\"p\n\025FetchMetaDataResponse\0224\n\005files\030\001 \003(" +
      "\0132%.com.ruyuan.dfs.common.proto.Metadata" +
      "\022\021\n\tcompleted\030\002 \001(\010\022\016\n\006nodeId\030\003 \001(\005\"\272\001\n\010" +
      "Metadata\022\020\n\010fileName\030\001 \001(\t\022\014\n\004type\030\002 \001(\005" +
      "\022\020\n\010hostname\030\003 \001(\t\022\020\n\010fileSize\030\004 \001(\003\022=\n\004" +
      "attr\030\005 \003(\0132/.com.ruyuan.dfs.common.proto" +
      ".Metadata.AttrEntry\032+\n\tAttrEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"?\n$RebalanceFet" +
      "chMetadataCompletedEvent\022\027\n\017rebalanceNod",
      "eId\030\001 \001(\005\"[\n%RebalanceRemoveMetadataComp" +
      "letedEvent\022\027\n\017rebalanceNodeId\030\001 \001(\005\022\031\n\021c" +
      "urrentNameNodeId\030\002 \001(\005\"#\n\022TrashResumeReq" +
      "uest\022\r\n\005files\030\001 \003(\t\"(\n\023TrashResumeRespon" +
      "se\022\021\n\tfileCount\030\001 \001(\005\"a\n\017UserChangeEvent" +
      "\022\021\n\teventType\030\001 \001(\005\022;\n\nuserEntity\030\002 \001(\0132" +
      "\'.com.ruyuan.dfs.common.proto.UserEntity" +
      "\"\203\001\n\nUserEntity\022\020\n\010username\030\001 \001(\t\022\016\n\006sec" +
      "ret\030\002 \001(\t\022?\n\007storage\030\003 \001(\0132..com.ruyuan." +
      "dfs.common.proto.UserStorageEntity\022\022\n\ncr",
      "eateTime\030\004 \001(\003\"N\n\021UserStorageEntity\022\023\n\013s" +
      "torageSize\030\001 \001(\003\022\021\n\tfileCount\030\002 \001(\005\022\021\n\td" +
      "ataNodes\030\003 \003(\t\"I\n\010UserList\022=\n\014userEntiti" +
      "es\030\001 \003(\0132\'.com.ruyuan.dfs.common.proto.U" +
      "serEntity\"\037\n\017ListFileRequest\022\014\n\004path\030\001 \001" +
      "(\t\"k\n\014NameNodeInfo\022\016\n\006nodeId\030\001 \001(\005\022\020\n\010ho" +
      "stname\030\002 \001(\t\022\020\n\010httpPort\030\003 \001(\005\022\017\n\007nioPor" +
      "t\030\004 \001(\005\022\026\n\016backupNodeInfo\030\005 \001(\t\"\'\n\026Remov" +
      "eFileOrDirRequest\022\r\n\005files\030\001 \003(\t\",\n\027Remo" +
      "veFileOrDirResponse\022\021\n\tfileCount\030\001 \001(\005\"2",
      "\n\036FetchDataNodeByFilenameRequest\022\020\n\010file" +
      "name\030\001 \001(\t\"[\n\037FetchDataNodeByFilenameRes" +
      "ponse\0228\n\tdatanodes\030\001 \003(\0132%.com.ruyuan.df" +
      "s.common.proto.DataNode\"<\n\024AddReplicaNum" +
      "Request\022\020\n\010filename\030\001 \001(\t\022\022\n\nreplicaNum\030" +
      "\002 \001(\005\"\231\002\n\022ClientNameNodeInfo\022K\n\006config\030\001" +
      " \003(\0132;.com.ruyuan.dfs.common.proto.Clien" +
      "tNameNodeInfo.ConfigEntry\022I\n\005slots\030\002 \003(\013" +
      "2:.com.ruyuan.dfs.common.proto.ClientNam" +
      "eNodeInfo.SlotsEntry\022\016\n\006backup\030\003 \001(\t\032-\n\013",
      "ConfigEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\032,\n\nSlotsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030" +
      "\002 \001(\005:\0028\001\"Z\n\022ClientDataNodeInfo\022D\n\017clien" +
      "tDataNodes\030\001 \003(\0132+.com.ruyuan.dfs.common" +
      ".proto.ClientDataNode\"m\n\016ClientDataNode\022" +
      "\016\n\006nodeId\030\001 \001(\005\022\020\n\010hostname\030\002 \001(\t\022\026\n\016sto" +
      "redDataSize\030\003 \001(\003\022\021\n\tfreeSpace\030\004 \001(\003\022\016\n\006" +
      "status\030\005 \001(\005B!\n\035com.ruyuan.dfs.model.nam" +
      "enodeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dfs.common.model.common.Commons.getDescriptor(),
          com.dfs.common.model.datanode.Datanode.getDescriptor(),
        }, assigner);
    internal_static_com_ruyuan_dfs_common_proto_ControllerVote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan_dfs_common_proto_ControllerVote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ControllerVote_descriptor,
        new String[] { "VoterNodeId", "ControllerNodeId", "VoteRound", "Force", });
    internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor,
        new String[] { "NameNodeId", "NumOfNode", "Server", "Servers", "IsClient", });
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_descriptor,
        new String[] { "OldSlots", "NewSlots", "Rebalance", "RebalanceNodeId", });
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_OldSlotsEntry_descriptor =
      internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_descriptor.getNestedTypes().get(0);
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_OldSlotsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_OldSlotsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_NewSlotsEntry_descriptor =
      internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_descriptor.getNestedTypes().get(1);
    internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_NewSlotsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NameNodeSlots_NewSlotsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_ruyuan_dfs_common_proto_NewPeerNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ruyuan_dfs_common_proto_NewPeerNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NewPeerNodeInfo_descriptor,
        new String[] { "Requests", "Users", });
    internal_static_com_ruyuan_dfs_common_proto_RebalanceSlotsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ruyuan_dfs_common_proto_RebalanceSlotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RebalanceSlotsRequest_descriptor,
        new String[] { "NameNodeId", });
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataRequest_descriptor,
        new String[] { "Slots", "NodeId", });
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor,
        new String[] { "Files", "Completed", "NodeId", });
    internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_ruyuan_dfs_common_proto_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor,
        new String[] { "FileName", "Type", "Hostname", "FileSize", "Attr", });
    internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_descriptor =
      internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_ruyuan_dfs_common_proto_RebalanceFetchMetadataCompletedEvent_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_ruyuan_dfs_common_proto_RebalanceFetchMetadataCompletedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RebalanceFetchMetadataCompletedEvent_descriptor,
        new String[] { "RebalanceNodeId", });
    internal_static_com_ruyuan_dfs_common_proto_RebalanceRemoveMetadataCompletedEvent_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_ruyuan_dfs_common_proto_RebalanceRemoveMetadataCompletedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RebalanceRemoveMetadataCompletedEvent_descriptor,
        new String[] { "RebalanceNodeId", "CurrentNameNodeId", });
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_TrashResumeRequest_descriptor,
        new String[] { "Files", });
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_ruyuan_dfs_common_proto_TrashResumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_TrashResumeResponse_descriptor,
        new String[] { "FileCount", });
    internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor,
        new String[] { "EventType", "UserEntity", });
    internal_static_com_ruyuan_dfs_common_proto_UserEntity_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_ruyuan_dfs_common_proto_UserEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_UserEntity_descriptor,
        new String[] { "Username", "Secret", "Storage", "CreateTime", });
    internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor,
        new String[] { "StorageSize", "FileCount", "DataNodes", });
    internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_ruyuan_dfs_common_proto_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor,
        new String[] { "UserEntities", });
    internal_static_com_ruyuan_dfs_common_proto_ListFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_ruyuan_dfs_common_proto_ListFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ListFileRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_ruyuan_dfs_common_proto_NameNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_ruyuan_dfs_common_proto_NameNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_NameNodeInfo_descriptor,
        new String[] { "NodeId", "Hostname", "HttpPort", "NioPort", "BackupNodeInfo", });
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirRequest_descriptor,
        new String[] { "Files", });
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RemoveFileOrDirResponse_descriptor,
        new String[] { "FileCount", });
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameRequest_descriptor,
        new String[] { "Filename", });
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_FetchDataNodeByFilenameResponse_descriptor,
        new String[] { "Datanodes", });
    internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor,
        new String[] { "Filename", "ReplicaNum", });
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor,
        new String[] { "Config", "Slots", "Backup", });
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_descriptor =
      internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor.getNestedTypes().get(0);
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_descriptor =
      internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor.getNestedTypes().get(1);
    internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor,
        new String[] { "ClientDataNodes", });
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNode_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_ruyuan_dfs_common_proto_ClientDataNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ClientDataNode_descriptor,
        new String[] { "NodeId", "Hostname", "StoredDataSize", "FreeSpace", "Status", });
    com.dfs.common.model.common.Commons.getDescriptor();
    com.dfs.common.model.datanode.Datanode.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
