// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.NameNodeAwareRequest}
 */
public  final class NameNodeAwareRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.NameNodeAwareRequest)
        NameNodeAwareRequestOrBuilder {
  // Use NameNodeAwareRequest.newBuilder() to construct.
  private NameNodeAwareRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NameNodeAwareRequest() {
    nameNodeId_ = 0;
    numOfNode_ = 0;
    server_ = "";
    servers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    isClient_ = false;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NameNodeAwareRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            nameNodeId_ = input.readInt32();
            break;
          }
          case 16: {

            numOfNode_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            server_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              servers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            servers_.add(s);
            break;
          }
          case 40: {

            isClient_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        servers_ = servers_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dfs.common.model.namenode.NameNodeAwareRequest.class, com.dfs.common.model.namenode.NameNodeAwareRequest.Builder.class);
  }

  private int bitField0_;
  public static final int NAMENODEID_FIELD_NUMBER = 1;
  private int nameNodeId_;
  /**
   * <code>optional int32 nameNodeId = 1;</code>
   */
  public int getNameNodeId() {
    return nameNodeId_;
  }

  public static final int NUMOFNODE_FIELD_NUMBER = 2;
  private int numOfNode_;
  /**
   * <code>optional int32 numOfNode = 2;</code>
   */
  public int getNumOfNode() {
    return numOfNode_;
  }

  public static final int SERVER_FIELD_NUMBER = 3;
  private volatile Object server_;
  /**
   * <code>optional string server = 3;</code>
   */
  public String getServer() {
    Object ref = server_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      server_ = s;
      return s;
    }
  }
  /**
   * <code>optional string server = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServerBytes() {
    Object ref = server_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      server_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList servers_;
  /**
   * <code>repeated string servers = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getServersList() {
    return servers_;
  }
  /**
   * <code>repeated string servers = 4;</code>
   */
  public int getServersCount() {
    return servers_.size();
  }
  /**
   * <code>repeated string servers = 4;</code>
   */
  public String getServers(int index) {
    return servers_.get(index);
  }
  /**
   * <code>repeated string servers = 4;</code>
   */
  public com.google.protobuf.ByteString
      getServersBytes(int index) {
    return servers_.getByteString(index);
  }

  public static final int ISCLIENT_FIELD_NUMBER = 5;
  private boolean isClient_;
  /**
   * <code>optional bool isClient = 5;</code>
   */
  public boolean getIsClient() {
    return isClient_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nameNodeId_ != 0) {
      output.writeInt32(1, nameNodeId_);
    }
    if (numOfNode_ != 0) {
      output.writeInt32(2, numOfNode_);
    }
    if (!getServerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, server_);
    }
    for (int i = 0; i < servers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, servers_.getRaw(i));
    }
    if (isClient_ != false) {
      output.writeBool(5, isClient_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nameNodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nameNodeId_);
    }
    if (numOfNode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numOfNode_);
    }
    if (!getServerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, server_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < servers_.size(); i++) {
        dataSize += computeStringSizeNoTag(servers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getServersList().size();
    }
    if (isClient_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isClient_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dfs.common.model.namenode.NameNodeAwareRequest)) {
      return super.equals(obj);
    }
    com.dfs.common.model.namenode.NameNodeAwareRequest other = (com.dfs.common.model.namenode.NameNodeAwareRequest) obj;

    boolean result = true;
    result = result && (getNameNodeId()
        == other.getNameNodeId());
    result = result && (getNumOfNode()
        == other.getNumOfNode());
    result = result && getServer()
        .equals(other.getServer());
    result = result && getServersList()
        .equals(other.getServersList());
    result = result && (getIsClient()
        == other.getIsClient());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NAMENODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNameNodeId();
    hash = (37 * hash) + NUMOFNODE_FIELD_NUMBER;
    hash = (53 * hash) + getNumOfNode();
    hash = (37 * hash) + SERVER_FIELD_NUMBER;
    hash = (53 * hash) + getServer().hashCode();
    if (getServersCount() > 0) {
      hash = (37 * hash) + SERVERS_FIELD_NUMBER;
      hash = (53 * hash) + getServersList().hashCode();
    }
    hash = (37 * hash) + ISCLIENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsClient());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dfs.common.model.namenode.NameNodeAwareRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dfs.common.model.namenode.NameNodeAwareRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.NameNodeAwareRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.NameNodeAwareRequest)
      com.dfs.common.model.namenode.NameNodeAwareRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dfs.common.model.namenode.NameNodeAwareRequest.class, com.dfs.common.model.namenode.NameNodeAwareRequest.Builder.class);
    }

    // Construct using com.dfs.common.model.namenode.NameNodeAwareRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      nameNodeId_ = 0;

      numOfNode_ = 0;

      server_ = "";

      servers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      isClient_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dfs.common.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_NameNodeAwareRequest_descriptor;
    }

    public com.dfs.common.model.namenode.NameNodeAwareRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    public com.dfs.common.model.namenode.NameNodeAwareRequest build() {
      com.dfs.common.model.namenode.NameNodeAwareRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dfs.common.model.namenode.NameNodeAwareRequest buildPartial() {
      com.dfs.common.model.namenode.NameNodeAwareRequest result = new com.dfs.common.model.namenode.NameNodeAwareRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.nameNodeId_ = nameNodeId_;
      result.numOfNode_ = numOfNode_;
      result.server_ = server_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        servers_ = servers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.servers_ = servers_;
      result.isClient_ = isClient_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dfs.common.model.namenode.NameNodeAwareRequest) {
        return mergeFrom((com.dfs.common.model.namenode.NameNodeAwareRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dfs.common.model.namenode.NameNodeAwareRequest other) {
      if (other == getDefaultInstance()) return this;
      if (other.getNameNodeId() != 0) {
        setNameNodeId(other.getNameNodeId());
      }
      if (other.getNumOfNode() != 0) {
        setNumOfNode(other.getNumOfNode());
      }
      if (!other.getServer().isEmpty()) {
        server_ = other.server_;
        onChanged();
      }
      if (!other.servers_.isEmpty()) {
        if (servers_.isEmpty()) {
          servers_ = other.servers_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureServersIsMutable();
          servers_.addAll(other.servers_);
        }
        onChanged();
      }
      if (other.getIsClient() != false) {
        setIsClient(other.getIsClient());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dfs.common.model.namenode.NameNodeAwareRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dfs.common.model.namenode.NameNodeAwareRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int nameNodeId_ ;
    /**
     * <code>optional int32 nameNodeId = 1;</code>
     */
    public int getNameNodeId() {
      return nameNodeId_;
    }
    /**
     * <code>optional int32 nameNodeId = 1;</code>
     */
    public Builder setNameNodeId(int value) {
      
      nameNodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 nameNodeId = 1;</code>
     */
    public Builder clearNameNodeId() {
      
      nameNodeId_ = 0;
      onChanged();
      return this;
    }

    private int numOfNode_ ;
    /**
     * <code>optional int32 numOfNode = 2;</code>
     */
    public int getNumOfNode() {
      return numOfNode_;
    }
    /**
     * <code>optional int32 numOfNode = 2;</code>
     */
    public Builder setNumOfNode(int value) {
      
      numOfNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 numOfNode = 2;</code>
     */
    public Builder clearNumOfNode() {
      
      numOfNode_ = 0;
      onChanged();
      return this;
    }

    private Object server_ = "";
    /**
     * <code>optional string server = 3;</code>
     */
    public String getServer() {
      Object ref = server_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        server_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      Object ref = server_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public Builder setServer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      server_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public Builder clearServer() {
      
      server_ = getDefaultInstance().getServer();
      onChanged();
      return this;
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public Builder setServerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      server_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList servers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureServersIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        servers_ = new com.google.protobuf.LazyStringArrayList(servers_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getServersList() {
      return servers_.getUnmodifiableView();
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public int getServersCount() {
      return servers_.size();
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public String getServers(int index) {
      return servers_.get(index);
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServersBytes(int index) {
      return servers_.getByteString(index);
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public Builder setServers(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServersIsMutable();
      servers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public Builder addServers(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureServersIsMutable();
      servers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public Builder addAllServers(
        Iterable<String> values) {
      ensureServersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, servers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public Builder clearServers() {
      servers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string servers = 4;</code>
     */
    public Builder addServersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureServersIsMutable();
      servers_.add(value);
      onChanged();
      return this;
    }

    private boolean isClient_ ;
    /**
     * <code>optional bool isClient = 5;</code>
     */
    public boolean getIsClient() {
      return isClient_;
    }
    /**
     * <code>optional bool isClient = 5;</code>
     */
    public Builder setIsClient(boolean value) {
      
      isClient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isClient = 5;</code>
     */
    public Builder clearIsClient() {
      
      isClient_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.NameNodeAwareRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.NameNodeAwareRequest)
  private static final com.dfs.common.model.namenode.NameNodeAwareRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dfs.common.model.namenode.NameNodeAwareRequest();
  }

  public static com.dfs.common.model.namenode.NameNodeAwareRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NameNodeAwareRequest>
      PARSER = new com.google.protobuf.AbstractParser<NameNodeAwareRequest>() {
    public NameNodeAwareRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NameNodeAwareRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NameNodeAwareRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NameNodeAwareRequest> getParserForType() {
    return PARSER;
  }

  public com.dfs.common.model.namenode.NameNodeAwareRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

