// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface NewPeerNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.NewPeerNodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.RegisterRequest requests = 1;</code>
   */
  java.util.List<com.dfs.common.model.datanode.RegisterRequest> 
      getRequestsList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.RegisterRequest requests = 1;</code>
   */
  com.dfs.common.model.datanode.RegisterRequest getRequests(int index);
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.RegisterRequest requests = 1;</code>
   */
  int getRequestsCount();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.RegisterRequest requests = 1;</code>
   */
  java.util.List<? extends com.dfs.common.model.datanode.RegisterRequestOrBuilder> 
      getRequestsOrBuilderList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.RegisterRequest requests = 1;</code>
   */
  com.dfs.common.model.datanode.RegisterRequestOrBuilder getRequestsOrBuilder(
      int index);

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity users = 2;</code>
   */
  java.util.List<com.dfs.common.model.namenode.UserEntity> 
      getUsersList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity users = 2;</code>
   */
  com.dfs.common.model.namenode.UserEntity getUsers(int index);
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity users = 2;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity users = 2;</code>
   */
  java.util.List<? extends com.dfs.common.model.namenode.UserEntityOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity users = 2;</code>
   */
  com.dfs.common.model.namenode.UserEntityOrBuilder getUsersOrBuilder(
      int index);
}
