// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface RebalanceRemoveMetadataCompletedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.RebalanceRemoveMetadataCompletedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 rebalanceNodeId = 1;</code>
   */
  int getRebalanceNodeId();

  /**
   * <code>optional int32 currentNameNodeId = 2;</code>
   */
  int getCurrentNameNodeId();
}
