// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface RemoveFileOrDirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.RemoveFileOrDirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 fileCount = 1;</code>
   */
  int getFileCount();
}
