// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface RemoveFileOrDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.RemoveFileOrDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string files = 1;</code>
   */
  java.util.List<String>
      getFilesList();
  /**
   * <code>repeated string files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated string files = 1;</code>
   */
  String getFiles(int index);
  /**
   * <code>repeated string files = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilesBytes(int index);
}
