// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package com.dfs.common.model.namenode;

public interface UserStorageEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.UserStorageEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 storageSize = 1;</code>
   */
  long getStorageSize();

  /**
   * <code>optional int32 fileCount = 2;</code>
   */
  int getFileCount();

  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  java.util.List<String>
      getDataNodesList();
  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  int getDataNodesCount();
  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  String getDataNodes(int index);
  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataNodesBytes(int index);
}
