// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

package com.dfs.common.model.datanode;

public final class Datanode {
  private Datanode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ReplicaCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ReplicaCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_ReportCompleteStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_ReportCompleteStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_FileMetaInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_FileMetaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruyuan_dfs_common_proto_PeerNodeAwareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruyuan_dfs_common_proto_PeerNodeAwareRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016datanode.proto\022\033com.ruyuan.dfs.common." +
      "proto\"\201\001\n\017RegisterRequest\022\020\n\010hostname\030\001 " +
      "\001(\t\022\017\n\007nioPort\030\002 \001(\005\022\020\n\010httpPort\030\003 \001(\005\022\026" +
      "\n\016storedDataSize\030\004 \001(\003\022\021\n\tfreeSpace\030\005 \001(" +
      "\003\022\016\n\006nodeId\030\006 \001(\005\"$\n\020HeartbeatRequest\022\020\n" +
      "\010hostname\030\001 \001(\t\"R\n\021HeartbeatResponse\022=\n\010" +
      "commands\030\001 \003(\0132+.com.ruyuan.dfs.common.p" +
      "roto.ReplicaCommand\"S\n\016ReplicaCommand\022\020\n" +
      "\010filename\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\014\n\004por" +
      "t\030\003 \001(\005\022\017\n\007command\030\004 \001(\005\"T\n\034InformReplic",
      "aReceivedRequest\022\020\n\010hostname\030\001 \001(\t\022\020\n\010fi" +
      "lename\030\002 \001(\t\022\020\n\010fileSize\030\003 \001(\003\"\204\001\n Repor" +
      "tCompleteStorageInfoRequest\022\020\n\010hostname\030" +
      "\001 \001(\t\022<\n\tfileInfos\030\002 \003(\0132).com.ruyuan.df" +
      "s.common.proto.FileMetaInfo\022\020\n\010finished\030" +
      "\003 \001(\010\"2\n\014FileMetaInfo\022\020\n\010filename\030\001 \001(\t\022" +
      "\020\n\010fileSize\030\002 \001(\003\"@\n\024PeerNodeAwareReques" +
      "t\022\024\n\014peerDataNode\030\001 \001(\t\022\022\n\ndataNodeId\030\002 " +
      "\001(\005B!\n\035com.ruyuan.dfs.model.datanodeP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ruyuan_dfs_common_proto_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruyuan_dfs_common_proto_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_RegisterRequest_descriptor,
        new String[] { "Hostname", "NioPort", "HttpPort", "StoredDataSize", "FreeSpace", "NodeId", });
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_HeartbeatRequest_descriptor,
        new String[] { "Hostname", });
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ruyuan_dfs_common_proto_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_HeartbeatResponse_descriptor,
        new String[] { "Commands", });
    internal_static_com_ruyuan_dfs_common_proto_ReplicaCommand_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ruyuan_dfs_common_proto_ReplicaCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ReplicaCommand_descriptor,
        new String[] { "Filename", "Hostname", "Port", "Command", });
    internal_static_com_ruyuan_dfs_common_proto_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ruyuan_dfs_common_proto_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_InformReplicaReceivedRequest_descriptor,
        new String[] { "Hostname", "Filename", "FileSize", });
    internal_static_com_ruyuan_dfs_common_proto_ReportCompleteStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ruyuan_dfs_common_proto_ReportCompleteStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_ReportCompleteStorageInfoRequest_descriptor,
        new String[] { "Hostname", "FileInfos", "Finished", });
    internal_static_com_ruyuan_dfs_common_proto_FileMetaInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ruyuan_dfs_common_proto_FileMetaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_FileMetaInfo_descriptor,
        new String[] { "Filename", "FileSize", });
    internal_static_com_ruyuan_dfs_common_proto_PeerNodeAwareRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_ruyuan_dfs_common_proto_PeerNodeAwareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruyuan_dfs_common_proto_PeerNodeAwareRequest_descriptor,
        new String[] { "PeerDataNode", "DataNodeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
