// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

package com.dfs.common.model.datanode;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ReplicaCommand commands = 1;</code>
   */
  java.util.List<com.dfs.common.model.datanode.ReplicaCommand> 
      getCommandsList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ReplicaCommand commands = 1;</code>
   */
  com.dfs.common.model.datanode.ReplicaCommand getCommands(int index);
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ReplicaCommand commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ReplicaCommand commands = 1;</code>
   */
  java.util.List<? extends com.dfs.common.model.datanode.ReplicaCommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ReplicaCommand commands = 1;</code>
   */
  com.dfs.common.model.datanode.ReplicaCommandOrBuilder getCommandsOrBuilder(
      int index);
}
