// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

package com.dfs.common.model.datanode;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string hostname = 1;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();
}
